services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - pong-network
    ports:
      - "9000:9000"
    volumes:
      - frontend_dist:/app/dist
    restart: always

  backend:
    build: ./backend
    container_name: backend
    networks:
      - pong-network
    volumes:
      - sqlite_data:/app/data
    env_file:
      - ../secrets/.env
    expose:
      - "3000"
    restart: always


volumes:
  sqlite_data:
  frontend_dist:

networks:
  pong-network:
